### ISSUE TITLE
Need API method to get whether a user has rated comment (without rating it)

### ISSUE THREAD

**Issue by stanostr** [playdafuture/YouDMC#23]
In order to help us highlight the appropriate thumbs up/down button upon a user opening a video, an API method to see whether a user has rated a given comment would be helpful.

**Comment by shawnyang610** [comment]
make sense
@playdafuture anything else to add before I start?

**Comment by playdafuture** [comment]
No other feature is needed.
The only question here is how to implement. Querying each and every <message, user id> pair is obviously not efficient. 
So I think one possible way, is to include optional argument into the existing get comments API: 
when the get method is provided with an auth token (maybe in the headers), 
then the messages (root or replies alike) will include an extra field "voted" or something,
with value {+1, 0, or -1}
Thanks

**Comment by shawnyang610** [comment]
Gotcha, you should also talk to Stan, I want all of us to be on the same
page. because I'm not going to make an API just for one of you.  if I make
it, both of you should to implement it. or it's just a waste of my time.
apparently he's got a couple of ideas, you should decide if you want it too

**Comment by shawnyang610** [comment]
adding 'rated' param in get/comments and get/user_comments endpoints 139e420d1018cce3d3fb27a7b49a91668cdc81a5

for get/comments and get/user_comments endpoints
* optional header: Authorization:Bearer access_token ("rated" variable works only when an valid access_token is present)

either include access_token or not include it.
if access_token is invalid, it returns an error message instead of just  calling the end point as if no access_token is present
"rated" variable is a boolean type
returns true if the logged in user has either rate 1 or -1
false for all other situations
